### ISSUE TITLE
Plane model reference frame 

### ISSUE THREAD

**Issue by jibweb** [v4r-tuwien/table_plane_extractor#5]
Currently, the GetTablePlaneExtractor service returns plane models that are only valid in the `base_frame` (because the point cloud is itself transformed to that frame) but that's not clearly communicated in the returned message (the plane message does not have a header attached). This is a confusing behavior!

**Comment by lexihaberl** [comment]
Fixed in a2ece6c20a59271d43c41202966b26a5d5fa1449
