### ISSUE TITLE
Investigate RANSAC Issue

### ISSUE THREAD

**Issue by lexihaberl** [v4r-tuwien/table_plane_extractor#6]
![table_plane_extractor_issue](https://github.com/v4r-tuwien/table_plane_extractor/assets/74511314/3400eb1d-b681-4b57-82ca-721bd0c94b8b)

The RANSAC plane estimation is sometimes skewed (green BB). This results in not all table points being filtered, leading to the table points being detected as part of an object (blue BB).

This happens more often when the robot is looking along the diagonal of the table.

**Comment by jibweb** [comment]
If you can collect a few samples where it happens, that would be helpful for debug. RANSAC is RAndom SAmple Consensus, emphasis on the random, so it's possible that the number of iteration set is not sufficient to find the more optimal model. We can also look at different methods for plane extraction, as we had them in the old v4r library:
https://github.com/v4r-tuwien/v4r/tree/master/modules/segmentation/include/v4r/segmentation (plane_extractor...)
